### ISSUE TITLE
v1/aspects endpoint - array support

### ISSUE THREAD

**Issue by kamilsmuga** [salesforce/refocus#297]
Hi - is there a support to POST multiple aspects at once? I'm setting up Refocus from scratch and finding pushing all aspects one by one very manual

**Comment by iamigo** [comment]
I'm definitely supportive of adding those kinds of "bulk" API extensions, but we haven't made them a priority since there is workaround.

If you wanted to contribute to Refocus, you could implement this with pretty minor changes to /api/v1/swagger.yaml, /api/v1/controllers/aspects, plus new tests under /tests/api/v1/aspects.

**Comment by kamilsmuga** [comment]
is any controller using doPost (api/v1/helpers/verbs/doPost.js) to insert an array of objects? 
If yes, then I'll try to fix the error from line 50 - props.model.create is executed on an array and throws the error - 'TypeError: this.build(...).save is not a function'.
If no, what's the best way to proceed? One option would be to create a doPostInBulk.js in helpers and make it call doPost in a loop. @iamigo can you advise on the best way to implement this?

**Comment by kamilsmuga** [comment]
nvm - found a clean way to do it. There's a "model.bulkCreate" method from sequelize that can take the whole array and do a proper bulk. 

Fighting with tests. For some reason, validateJsonSchema doesn't kick off for relatedLinks in db/model/aspect.js after making the above change. Investigating

**Comment by kamilsmuga** [comment]
Okay - the validation is turned off by default for bulkCreate (http://docs.sequelizejs.com/en/latest/docs/instances/#working-in-bulk-creating-updating-and-destroying-multiple-rows-at-once).

**Comment by kamilsmuga** [comment]
I turned on the validators and for some reason the response to request
``` 
POST v1/aspects
{ "name": "___Pressure",
  "timeout": "110s",
  "relatedLinks":
   [ { "name": "link1", "url": "https://samples.com" },
     { "name": "link1", "url": "https://samples.com" } ] }
```

is generated as HTML 

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Error: Response validation failed: invalid content type (text/html). &nbsp;These are valid: application/json
            <br> &nbsp; &nbsp;at Object.module.exports.validateContentType (/Users/ksmuga/workspace/refocus/node_modules/swagger-tools/lib/validators.js:239:11)
            <br> &nbsp; &nbsp;at ServerResponse.res.end (/Users/ksmuga/workspace/refocus/node_modules/swagger-tools/middleware/swagger-validator.js:202:20)
            <br> &nbsp; &nbsp;at write (/Users/ksmuga/workspace/refocus/node_modules/finalhandler/index.js:266:9)
            <br> &nbsp; &nbsp;at send (/Users/ksmuga/workspace/refocus/node_modules/finalhandler/index.js:270:5)
            <br> &nbsp; &nbsp;at Immediate.&lt;anonymous&gt; (/Users/ksmuga/workspace/refocus/node_modules/finalhandler/index.js:135:5)
            <br> &nbsp; &nbsp;at Immediate.&lt;anonymous&gt; (/Users/ksmuga/workspace/refocus/node_modules/express/lib/router/index.js:635:15)
            <br> &nbsp; &nbsp;at runCallback (timers.js:651:20)
            <br> &nbsp; &nbsp;at tryOnImmediate (timers.js:622:5)
            <br> &nbsp; &nbsp;at processImmediate [as _immediateCallback] (timers.js:594:5)
        </pre>
    </body>
</html>
```

and Swagger complains about it.
```
  express:router swaggerMetadata  : /v1/aspects +11ms
  swagger-tools:middleware:metadata POST /v1/aspects +2s
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +0ms
  swagger-tools:middleware:metadata   Processing Parameters +1ms
  swagger-tools:middleware:metadata     queryBody +1ms
  swagger-tools:middleware:metadata       Type: array +0ms
  swagger-tools:middleware:metadata       Value provided: true +0ms
  swagger-tools:middleware:metadata       Value: [object Object] +1ms
  express:router swaggerValidator  : /v1/aspects +3ms
  swagger-tools:middleware:validator POST /v1/aspects +0ms
  swagger-tools:middleware:validator   Will process: yes +0ms
  swagger-tools:middleware:validator   Request validation: +0ms
  swagger-tools:middleware:validator     Validation: succeeded +4ms
  express:router swaggerRouter  : /v1/aspects +4ms
  swagger-tools:middleware:router POST /v1/aspects +1ms
  swagger-tools:middleware:router   Will process: yes +0ms
  swagger-tools:middleware:router   Route handler: aspects_postAspect +0ms
  swagger-tools:middleware:router     Missing: no +0ms
  swagger-tools:middleware:router     Ignored: no +0ms
  swagger-tools:middleware:router     Using mock: no +0ms
  express:router swaggerUI  : /v1/aspects +8ms
  express:router errorHandler  : /v1/aspects +0ms
  finalhandler default 404 +7ms
  swagger-tools:middleware:validator   Response validation: +1ms
  swagger-tools:middleware:validator     Validation: failed +0ms
  swagger-tools:middleware:validator   Reason: Invalid content type (text/html).  These are valid: application/json +1ms
  swagger-tools:middleware:validator   Stack: +0ms
  swagger-tools:middleware:validator       at Object.module.exports.validateContentType (/Users/ksmuga/workspace/refocus/node_modules/swagger-tools/lib/validators.js:239:11) +0ms
  swagger-tools:middleware:validator       at ServerResponse.res.end (/Users/ksmuga/workspace/refocus/node_modules/swagger-tools/middleware/swagger-validator.js:202:20) +0ms
  swagger-tools:middleware:validator       at write (/Users/ksmuga/workspace/refocus/node_modules/finalhandler/index.js:266:9) +0ms
  swagger-tools:middleware:validator       at send (/Users/ksmuga/workspace/refocus/node_modules/finalhandler/index.js:270:5) +5ms
  swagger-tools:middleware:validator       at Immediate.<anonymous> (/Users/ksmuga/workspace/refocus/node_modules/finalhandler/index.js:135:5) +0ms
  swagger-tools:middleware:validator       at Immediate.<anonymous> (/Users/ksmuga/workspace/refocus/node_modules/express/lib/router/index.js:635:15) +0ms
  swagger-tools:middleware:validator       at runCallback (timers.js:651:20) +0ms
  swagger-tools:middleware:validator       at tryOnImmediate (timers.js:622:5) +0ms
  swagger-tools:middleware:validator       at processImmediate [as _immediateCallback] (timers.js:594:5) +0ms
  finalhandler default 404 +1ms
  compression gzip compression +0ms
Error: Response validation failed: invalid content type (text/html).  These are valid: application/json
    at Object.module.exports.validateContentType (/Users/ksmuga/workspace/refocus/node_modules/swagger-tools/lib/validators.js:239:11)
    at ServerResponse.res.end (/Users/ksmuga/workspace/refocus/node_modules/swagger-tools/middleware/swagger-validator.js:202:20)
    at write (/Users/ksmuga/workspace/refocus/node_modules/finalhandler/index.js:266:9)
    at send (/Users/ksmuga/workspace/refocus/node_modules/finalhandler/index.js:270:5)
    at Immediate.<anonymous> (/Users/ksmuga/workspace/refocus/node_modules/finalhandler/index.js:135:5)
    at Immediate.<anonymous> (/Users/ksmuga/workspace/refocus/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

As the stack trace doesn't mention any of the Refocus code - I'm kinda stuck. This is the code I changed: https://github.com/kamilsmuga/refocus/commit/1679eb157a9e796d54ba0c3d1e936c3abc0ae64d
 I have to ask for some help in debugging @iamigo @shriramshankar

**Comment by iamigo** [comment]
@kamilsmuga - you can't *modify* the existing `POST /v1/aspects` endpoint (changing the request body from object to array) without rev'ing the API version, but you *can* add a new `POST /v1/aspects/bulk` endpoint.
